'''
1) Co-ordinate generator 
2) vertiports at specific location - generated by the co-ordinate generator 
3) UAV at vertiport 
4) UAV dynamics 
5) UAV controller 
6) Plotting mechanics 

'''



## PLOT ## 
# place vertiports at co-ordinates
# place UAV and move dynamics using st
# 
# 
#  







# Example usage:
# coordinates = get_coords(num_co_ords=6, distance=10)
# print(coordinates)